var namespacedata_p_a_r_c_1_1_store_1_1_enterprise_core_1_1_tag_data_points_1_1_unions =
[
    [ "TagDataPoints", "d1/d82/classdata_p_a_r_c_1_1_store_1_1_enterprise_core_1_1_tag_data_points_1_1_unions_1_1_tag_data_points.html", "d1/d82/classdata_p_a_r_c_1_1_store_1_1_enterprise_core_1_1_tag_data_points_1_1_unions_1_1_tag_data_points" ]
];